<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>      
        /*
            1. 错误的类型
                - Error:所有错误的父类型
                - ReferenceError: 引用的变量不存在
                - TypeError: 数据类型不正确的错误
                - RangeError: 数据值不再其所允许的范围内
                - SyntaxError: 语法错误

            2. 错误处理
                - 捕获错误： try ... catch
                - 跑出错误： throw error
            3. 错误对象
                - message属性：错误相关信息
                - stack属性：函数调用栈记录信息
        */
        //1.常见的内置错误
        // ReferenceError: 引用不存在的变量
        // console.log(a)
        // console.log('----') 没有捕获error下面的代码不会执行

        //TypeError: 数据类型不正确的错误
        // let b = null
        // console.log(b.xxx)  //要读属性必须是一个对象

        //RangeError: 数据值不再其所允许的范围内
        // function fn(){
        //     fn();//递归，这边是死循环
        // }
        // fn();
        //SyntaxError: 语法错误
        // const="""";

        //2.错误处理
            // 捕获错误： try ... catch
            try{
                let d;
                console.log(d.xxx)
            }catch(error){
                console.log(error.message);
                console.log(error.stack)
            }
            console.log("出错以后");

            // 抛出错误： throw error
            function something(){
                if(Date.now()%2===1){
                    console.log("当前时间为奇数，可以执行任务")
                }else{ //如果时间为偶数则抛出异常，由调用来处理
                    throw new Error("当前时间为偶数，无法执行任务")
                }
            }
            //捕获处理异常
            try{
                something()
            }catch(error){
                console.log(error.message)
            }



    </script>
</body>
</html>